#name: Deploy to Azure

#on:
#  push:
#    branches:
#      - main

#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2

#      - name: Login to Azure
#        uses: azure/login@v1
#       with:
#          client-id: ${{ secrets.AZURE_CLIENT_ID }}
#          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
#          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

#      - name: Deploy to Azure Web App
#        uses: azure/webapps-deploy@v3
#        with:
#          app-name: conexaoSensoresMQTT-API
#          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
